import {
  kaushan_script,
  inter,
  montserrat,
  poppins,
  noto_serif,
} from "./fonts";
import "./globals.scss";
import { Footer, Navbar, ProfileAndCart } from "./components/generalComponents";

export const metadata = {
  title: "B Furniture App",
  description: "Generated by dvelat codes",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${kaushan_script.variable} ${montserrat.variable} ${poppins.variable} ${noto_serif.variable}`}
      >
        <Navbar />
        <ProfileAndCart/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
