import {
  kaushan_script,
  inter,
  montserrat,
  poppins,
  noto_serif,
} from "./fonts";
import "./globals.scss";
import { Footer, Navbar, ProfileAndCart } from "./components/generalComponents";
import Cart from "./components/Cart/Cart";
import { AppContext } from "../context/AppContext";
import { CartProvider } from '../context/CartContext';
import Providers from "./store/Providers";

export const metadata = {
  title: "B Furniture App",
  description: "Generated by dvelat codes",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${kaushan_script.variable} ${montserrat.variable} ${poppins.variable} ${noto_serif.variable}`}
      >
        <Providers>
        <CartProvider>
          <Navbar />
          <Cart />
          <ProfileAndCart />
          {children}
          <Footer />
        </CartProvider>
        </Providers>
      </body>
    </html>
  );
}
